#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

dir="$( pwd )"

docker run \
    --rm \
    --mount type=bind,source="$dir",target=/data \
    --workdir /data \
    -it \
    gccgo-git \
    go "$@"
